# Generated by Django 3.2 on 2022-10-06 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='stamped_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='打刻時刻'),
        ),
    ]
