# Generated by Django 3.2 on 2023-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0003_auto_20221125_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='state',
            field=models.CharField(choices=[('0', '新規'), ('1', '申請中'), ('2', '承認済み'), ('3', '修正依頼')], default='0', max_length=1, verbose_name='ステータス'),
        ),
    ]
