# Generated by Django 3.2 on 2023-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0004_alter_timecard_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
