version: "3.9"

services:
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: containers/postgres/Dockerfile
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    restart: always
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/django/Dockerfile
    volumes:
      - .:/code
    expose:
      - "8000"
    command: sh -c "chmod 755 /code/entrypoint.sh && /code/entrypoint.sh"
    env_file:
      - .env.prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
  web:
    container_name: web
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    volumes:
      - ./static:/static
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app
volumes:
  db_data:
  static: