version: '3'

services:
  web:
    container_name: django
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5433:5432"

  nginx:
    container_name: nginx
    image: 1.22.0
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
        - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
